name

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -37,15 +37,19 @@ jobs:
     - uses: actions/checkout@v4
 
     - name: Log in to GHCR
-      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+      run: |
+        if [ -z "${{ secrets.GHCR_PAT }}" ]; then
+          echo "❌ ERROR: GHCR_PAT está vacío"
+          exit 1
+        fi
+        echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
 
     - name: Build Docker image
       run: |
-        docker build -t ${{ secrets.IMAGE_NAME }} .
-    
+        docker build -t ${{ secrets.IMAGE_NAME }}:latest .
+
     - name: Push Docker image to GHCR
       run: |
-        docker tag ${{ secrets.IMAGE_NAME }} ${{ secrets.IMAGE_NAME }}:latest
         docker push ${{ secrets.IMAGE_NAME }}:latest
 
 
@@ -55,6 +59,7 @@ jobs:
     environment: secret
 
     steps:
+
       - name: Checkout repo
         uses: actions/checkout@v3
 
@@ -83,7 +88,7 @@ jobs:
             echo "🔑 Logueando GHCR..."
             echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
 
-            echo "📥 Pull de la última imagen: ${{ secrets.IMAGE_NAME }}:latest"
+            echo "📥 Pull de la última imagen..."
             docker pull ${{ secrets.IMAGE_NAME }}:latest
 
             echo "🔥 Eliminando stack anterior..."
